name: m183_lb2_node
services:
  web:
      image: node:latest
      user: "node"
      working_dir: /home/node/app
      container_name: m183-lb2-web
      environment:
        - DBSERVER=m183-lb2-db
        - NODE_ENV=production
      ports:
        - "3000:3000"
      volumes:
        - type: bind
          source: ../todo-list-node
          target: /home/node/app
      command: "npm start"
      entrypoint: ["/bin/sh", "-c", "npm install && npm start"]